#!/usr/bin/env bash
# Original: http://frexx.de/xterm-256-notes/ [dead link 2013-11-21]
#           http://frexx.de/xterm-256-notes/data/colortable16.sh [dead link 2013-11-21]
# Modified by Aaron Griffin
# and further by Kazuo Teramoto
FGNAMES=(' black ' '  red  ' ' green ' ' yellow' '  blue ' 'magenta' '  cyan ' ' white ')
BGNAMES=('DFT' 'BLK' 'RED' 'GRN' 'YEL' 'BLU' 'MAG' 'CYN' 'WHT')

echo -e "     \033[30m┌──────────────────────────────────────────────────────────────────────────┐\033[m"
for b in {0..8}; do
  ((b>0)) && bg=$((b+39))

  echo -en "\033[37m ${BGNAMES[b]} \033[30m│ "
  
  for f in {0..7}; do
    echo -en "\033[${bg}m\033[$((f+30))m ${FGNAMES[f]} "
  done
  
  echo -en "\033[0;30m │"
  echo -en "\033[m\n\033[m     \033[30m│ "
  
  for f in {0..7}; do
    echo -en "\033[${bg}m\033[1;$((f+30))m ${FGNAMES[f]} "
  done

  echo -en "\033[m \033[30m│"
  echo -e "\033[m"

  ((b<8)) &&
  echo -e "     \033[30m├──────────────────────────────────────────────────────────────────────────┤\033[m"
done
echo -e "     \033[30m└──────────────────────────────────────────────────────────────────────────┘\033[m"
