#!/usr/bin/env bash

case $1 in
  
  openbox-session)
    exec openbox-session
  ;;

  *)

    ck-launch-session &
    dbus-launch &

    # disable that beep
    xset -b

    # merge .Xresources
    xrdb -merge $HOME/.Xresources &

    # set the cursor
    xsetroot -cursor_name left_ptr &

    # load fonts
    xset fp defaults
    xset +fp /usr/share/fonts/local
    xset +fp $HOME/.fonts
    xset fp rehash

    # set the background
    sh $HOME/.fehbg &

    # start urxvt daemon
    urxvtd -q -o -f &

    # start keyring daemon
    /usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh &

    # set panel fifo pipe
    export PANEL_FIFO=/tmp/panel-fifo
    ~/dotfiles/CrunchBang/Bar/init &

    sxhkd &
    exec bspwm

  ;;

esac
