#! /bin/sh

FIRST_DESK=1
DESKS="2 3 4 5"
bspc rename Desktop01 $FIRST_DESK
bspc add_in Monitor01 $DESKS

# bspc monitor -p 30 0 0 0

# bspc config top_padding         -22
bspc config border_width        5
bspc config window_gap          12
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config focused_border_color         '#1c728c'
bspc config active_border_color          '#186150'
bspc config presel_border_color          '#CFE5A7'
bspc config normal_locked_border_color   '#A2DCC3'
bspc config focused_locked_border_color  '#CFE5A7'
bspc config active_locked_border_color   '#FB7AA1'

urxvtc &
