#! /bin/sh

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 5)"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS
bspc monitor -p 30 0 0 0

bspc rule -a Gimp -d Eight --floating

bspc config split_ratio         0.50
bspc config border_width        2
bspc config window_gap          12
bspc config borderless_monocle  false
bspc config gapless_monocle     false

~/.bar/init &
