#! /bin/sh

# Desktops
FIRST_DESK=1
REMAINING_DESKS="$(seq 2 5)"
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS

# Make space for the panel
bspc monitor -p 25 0 0 0

# Window settings
bspc config border_width        5
bspc config window_gap          12
bspc config borderless_monocle  false
bspc config gapless_monocle     false

# Window colours
bspc config focused_border_color         '#1c728c'
bspc config active_border_color          '#186150'
bspc config presel_border_color          '#CFE5A7'
bspc config normal_locked_border_color   '#A2DCC3'
bspc config focused_locked_border_color  '#CFE5A7'
bspc config active_locked_border_color   '#FB7AA1'
