#!/bin/sh

# Config
PANEL_FIFO=/tmp/panel-fifo
B_CONFIG=~/.bspwm/bspwmrc
S_CONFIG=~/.bspwm/sxhkdrc

# Create pipe
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Listen for keyboard shortcuts
sxhkd -c "$S_CONFIG" &

# Start window manager
bspwm -s "$PANEL_FIFO" -c "$B_CONFIG" -p W

