#!/bin/sh
#
# ~/.xinitrc
#

# source xinitc.d scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# load .Xresources
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

# increase mouse acceleration
xset m 2

# disable that beep
xset -b

# Map caps to ctrl
setxkbmap -option "ctrl:nocaps,altwin:swap_lalt_lwin"

# Map control to control/escape
$HOME/Github/xcape/xcape -e 'Control_L=Escape'

# Load xmodmap for natural scrolling
xmodmap .Xmodmap

# add font paths
xset fp default
[[ -d /usr/share/fonts/local ]] && xset +fp /usr/share/fonts/local
[[ -d $HOME/.fonts ]] && xset +fp $HOME/.fonts
xset fp rehash

# set WM to a name with Java recognises
# wmname LG3D

# set background
sh $HOME/.fehbg

# start apps in background (only if not already running)
[[ -z "$(pidof urxvtd)" ]] && urxvtd -q -o -f
[[ -z "$(pidof bitlbee)" ]] && bitlbee -D

# start WM 
exec $HOME/.bspwm/start
