#!/usr/bin/env bash

# disable that beep
xset -b

# merge .Xresources
xrdb -merge $HOME/.Xresources &

# set the cursor
xsetroot -cursor_name left_ptr &

# load fonts
xset fp defaults
xset +fp /usr/share/fonts/local
xset +fp $HOME/.fonts
xset fp rehash

# set the background
feh --bg-tile "$HOME/dotfiles/Other/dark_stripe.png"

# start urxvt daemon
urxvtd -q -o -f &

# set panel fifo pipe
export PANEL_FIFO=/tmp/panel-fifo
~/dotfiles/Bar/init &

sxhkd &
exec bspwm
