#!/bin/sh

# Set the homedir
if [ -d /home/stayrad ]; then
  export HOME=/home/stayrad
else
  export HOME=/Users/Admin
fi

# Set the language
export LANG="en_NZ.UTF-8"

# Set the OS
OS="arch"

# Set the path
if [ -d /opt/local/bin ]; then
  PATH="$PATH:/usr/local/bin:/opt/local/bin:$HOME/.bin"
  OS="osx"
fi

# increase mouse acceleration
xset m 2

# disable that beep
xset -b

# edit key layout
[[ $OS = "arch" ]] && setxkbmap -option "ctrl:nocaps"
[[ -f $HOME/Github/xcape/xcape ]] && $HOME/Github/xcape/xcape -e "Control_L=Escape"

# set xmodmap
xmodmap $HOME/.Xmodmap

# merge .Xdefaults
xrdb -merge $HOME/.Xdefaults &

# Load xmodmap for natural scrolling
[[ -s $HOME/.Xmodmap ]] && xmodmap $HOME/.Xmodmap &

# Set the cursor
xsetroot -cursor_name left_ptr &

# Make sure fonts.dir exists
[[ ! -f $HOME/.fonts/fonts.dir ]] && mkfontdir $HOME/.fonts

# Use a normal cursor
xsetroot -cursor_name left_ptr

# add font paths
xset fp default
[[ -d /usr/share/fonts/local ]] && xset +fp /usr/share/fonts/local
[[ -d $HOME/.fonts ]] && xset +fp $HOME/.fonts
xset fp rehash

# set background
[[ -x $HOME/.fehbg ]] && $HOME/.fehbg &

# start apps in background (only if not already running)
[[ -z `pidof urxvtd` ]] && urxvtd -q -o -f &
exists bitlbee && [[ -z `pidof bitlbee` ]] && bitlbee -D
exists dropbox && [[ -z `pidof dropbox` ]] && dropbox start

# start WM
sxhkd -c $HOME/.bspwm/sxhkdrc &
exec bspwm -c $HOME/.bspwm/bspwmrc
