#!/usr/bin/env/bash

# Takes the input from reader and returns the formatted output

# Bar Colours
# 0 = background
# 1 = foreground
# 2 = grey bg
# 3 = grey text
# 4 = red
# 5 = green
# 6 = orange
# 7 = yellow
# 8 = blue
# 9 = magenta

# Icons
bat=$(echo -e '\ue006') # battery
clk=$(echo -e '\ue00E') # clock
sep="\f0$(echo -e '\u002')\fr"

battery=""
time=""

function print_right () {
  right="\r\f1${essid} ${sep} \f1${bat} ${battery}% ${sep} \f1${clk} ${time}\fr "
}

function print_title () {
  title="${line#?}"
}

function print_left () {
  left=""
  IFS=':'
  set -- ${line#?}
  while [ $# -gt 0 ] ; do
    item=$1
    name="    "
    case $item in
      O*)
        # focused occupied
        left="$left\\b1\\u1${name}\\br\\ur"
        ;;
      F*)
        # focused empty
        left="$left\\b0\\u0${name}\\br\\ur"
        ;;
      o*)
        # occupied
        left="$left\\f1${name}\\fr"
        ;;
      f*)
        # empty
        left="$left\\f0${name}\\fr"
        ;;
    esac
    shift
  done
}
