export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

xrdb -merge $HOME/.Xresources

sh $HOME/.fehbg

xset fp default
xset +fp /usr/share/fonts/local
xset +fp ~/.fonts
xset fp rehash

syndaemon -t -k -i 2 &

export PANEL_FIFO=/tmp/panel-fifo
$HOME/dotfiles/chromebook/bar/init &

sxhkd &
urxvtd -q -o -f &
exec bspwm
