import = [
  "~/dotfiles/apps/alacritty/termorrow_dark.toml",
  "~/dotfiles/apps/alacritty/termorrow_light.toml",
  "~/dotfiles/apps/alacritty/high_contrast.toml",
]

[font]
size = 8.0

[font.bold]
family = "sf mono"
style = "Bold"

[font.bold_italic]
family = "sf mono"
style = "Regular"

[font.italic]
family = "sf mono"
style = "Regular"

[font.normal]
family = "sf mono"
style = "Regular"
