import = ["~/dotfiles/apps/alacritty/colors/termorrow_dark.toml"]

[font]
size = 8.0

[font.bold]
family = "gomme"
style = "Bold"

[font.bold_italic]
family = "gomme"
style = "Regular"

[font.italic]
family = "gomme"
style = "Regular"

[font.normal]
family = "gomme"
style = "Regular"
