#!/usr/bin/env/bash

# Takes the input from reader and returns the formatted output

# Colors
c0="#FF08313B" # black
c1="#FFac4142" # red
c2="#FF90a959" # green
c3="#FFd28445" # yellow
c4="#FF6a9fb5" # blue
c5="#FFaa759f" # magenta
c6="#FF75b5aa" # cyan
c7="#FF969896" # white
c8="#FF134E5F" # + black
c9="#FFcc6666" # + red
c10="#FFb5bd68" # + green
c11="#FFf0c674" # + yellow
c12="#FF81a2be" # + blue
c13="#FFb294bb" # + magenta
c14="#FF8abeb7" # + cyan
c15="#FFc5c8c6" # + white

# Icons
bat=$(echo -e '\ue006') # battery
clk=$(echo -e '\ue00E') # clock
sep="%{F$c0}$(echo -e '\u002')%{F-}"

battery=""
time=""

function print_right () {
  right="%{r F$c1}${essid} ${sep} %{F$c1}${bat} ${battery}% ${sep} %{F$c1}${clk} ${time}%{F-} "
}

function print_title () {
  title="${line#?}"
}

function print_left () {
  left=""
  IFS=':'
  set -- ${line#?}
  while [ $# -gt 0 ] ; do
    item=$1
    name="    "
    case $item in
      O*)
        # focused occupied
        left="$left%{B$c1 U$c1}${name}%{B- U-}"
        ;;
      F*)
        # focused empty
        left="$left%{B$c0 U$c0}${name}%{B- U-}"
        ;;
      o*)
        # occupied
        left="$left%{F$c1}${name}%{F-}"
        ;;
      f*)
        # empty
        left="$left%{F$c0}${name}%{F-}"
        ;;
    esac
    shift
  done
}
