#!/usr/bin/env/bash

# Takes the input from reader and returns the formatted output

# Colors
c0='#FF08313B'  # black
c1='#FFac4142'  # red
c2='#FF90a959'  # green
c3='#FFd28445'  # yellow
c4='#FF6a9fb5'  # blue
c5='#FFaa759f'  # magenta
c6='#FF75b5aa'  # cyan
c7='#FF969896'  # white
c8='#FF134E5F'  # + black
c9='#FFcc6666'  # + red
c10='#FFb5bd68' # + green
c11='#FFf0c674' # + yellow
c12='#FF81a2be' # + blue
c13='#FFb294bb' # + magenta
c14='#FF8abeb7' # + cyan
c15='#FFc5c8c6' # + white

# Icons
btd=$(echo -e '\ue03F') # battery discharging
btc=$(echo -e '\ue09E') # battery charging
clk=$(echo -e '\ue081') # clock
cal=$(echo -e '\ue001') # calendar
net=$(echo -e '\ue048') # wifi
aru=$(echo -e '\ue023') # arrow up
ard=$(echo -e '\ue026') # arrow down
pac=$(echo -e '\ue02A') # pacman
dot=$(echo -e '\ue057') # square
dtt=$(echo -e '\ue005') # partial

battery_status=''
battery_charge=''
time=''
date=''
title=''

l=''
c=''
r=''

function print_left () {
  l="%{l}"
  [[ $title ]] && l="$l%{F$c6} $title %{F-}"
}

function print_right () {
  r="%{r}"
  [[ $essid ]] && r="$r  %{F$c2}$net $essid"

  r="$r  "
  if [[ $battery_charge -lt 20 ]]; then
    r="$r%{F$c1}"
  else
    r="$r%{F$c6}"
  fi
  if [[ $battery_status == Discharging ]]; then
    r="$r$btd"
  else
    r="$r$btc"
  fi
  r="$r $battery_charge%%"

  r="$r  %{F$c4}$cal $date"
  r="$r  %{F$c3}$clk $time"
  r="$r  %{F-}"
}

function print_center () {
  c='%{c}'
  IFS=':'
  set -- ${line#?}
  while [ $# -gt 0 ] ; do
    item=$1
    case $item in
      O*)
        # focused occupied
        c="$c%{F$c1} $dot %{B- U-}"
        ;;
      F*)
        # focused empty
        c="$c%{F$c1} $dtt %{B- U-}"
        ;;
      o*)
        # occupied
        c="$c%{F$c8} $dot %{F-}"
        ;;
      f*)
        # empty
        c="$c%{F$c8} $dtt %{F-}"
        ;;
    esac
    shift
  done
}
