#!/usr/bin/env bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Config
bspc config top_padding         25
bspc config border_width        3
bspc config window_gap          25
bspc config borderless_monocle  false
bspc config gapless_monocle     false

# Window colours

# focused window
bspc config focused_border_color         '#ac4142'

# unfocused window
bspc config normal_border_color          '#021b21'

# preselection border
bspc config presel_border_color          '#E8DFD6'
