source "${HOME}/dotfiles/apps/zsh/config.sh"
source "${HOME}/dotfiles/apps/zsh/git.sh"
source "${HOME}/dotfiles/apps/zsh/docker.sh"
source "${HOME}/.antibody.sh"
source "${HOME}/.config/fzf/fzf.zsh"
source "${HOME}/dotfiles/apps/zsh/stayradiated.sh"

# bun completions
[ -s "/home/admin/.bun/_bun" ] && source "/home/admin/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
