source "${HOME}/dotfiles/apps/zsh/config.sh"
source "${HOME}/dotfiles/apps/zsh/git.sh"
source "${HOME}/.antibody.sh"
source "${HOME}/.config/fzf/fzf.zsh"
source "${HOME}/dotfiles/apps/zsh/stayradiated.sh"

if [ -e /home/admin/.nix-profile/etc/profile.d/nix.sh ]; then
  source /home/admin/.nix-profile/etc/profile.d/nix.sh
fi



alias claude="/home/admin/.claude/local/claude"
