#!/usr/bin/env bash

BAR_SCRIPT=~/dotfiles/zenbook/bar/reader

# pipe bspwm info to bar
[ -e $PANEL_FIFO ] & rm $PANEL_FIFO
mkfifo $PANEL_FIFO

echo $PANEL_FIFO

# BSPWM events
bspc subscribe report | uq > $PANEL_FIFO &

# Active window title
xtitle -sf 'T%s\n' | uq > $PANEL_FIFO &

# Date
clock -s -i 60 -f 'D%a %d/%m' | uq > $PANEL_FIFO &

# Time
clock -s -i 10 -f 'C%H:%M' | uq > $PANEL_FIFO &

# Battery state
battery -s -i 5 -f 'B%s' | uq > $PANEL_FIFO &

# Battery percentage
battery -s -i 15 -f 'P%i' | uq > $PANEL_FIFO &

# Current wifi status
essid -w wlp2s0 -s -i 5 -f 'X%s' | uq > $PANEL_FIFO &

# Volume
volume -s -i 2 -f 'V%i' | uq > $PANEL_FIFO &

# Run bar
BAR_SIZE='1920x26+0+0'
BAR_FONT_1='-ypn-envypn-medium-r-normal--15-150-75-75-c-90-iso8859-1'
BAR_FONT_2='-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1'
BAR_FG='#FFa899c1'
BAR_BG='#FF040305'
BAR_OPTIONS="-g $BAR_SIZE -f $BAR_FONT_1 -f $BAR_FONT_2 -B $BAR_BG -F $BAR_FG -p"

cat $PANEL_FIFO | $BAR_SCRIPT | lemonbar $BAR_OPTIONS
