#!/usr/bin/env bash

bspc monitor MONITOR01 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor MONITOR01 -d 1 2 3 4 5 6 7 8 9 10

# Config
bspc config top_padding         -21
bspc config border_width        5
bspc config window_gap          35
bspc config borderless_monocle  false
bspc config gapless_monocle     false

# Window colours

# focused window
bspc config focused_border_color         '#15849E'

# unfocused window
bspc config normal_border_color          '#10323D'

# preselection border
bspc config presel_border_color          '#E8DFD6'
