#!/usr/bin/env bash

bspc monitor MONITOR01 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor MONITOR01 -d 1 2 3 4 5 6 7 8 9 10

# Config
bspc config split_ratio           0.50
bspc config top_padding           -21
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config auto_cancel           true
bspc config auto_alternate        false

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 4;
  bspc config -d $desktop window_gap 20;
done

# Window colours

# focused window
bspc config focused_border_color '#B0894A'

# unfocused window
bspc config normal_border_color  '#171207'

# preselection border
bspc config presel_border_color  '#599caa'
