#!/usr/bin/env bash

bspc monitor MONITOR01 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor MONITOR01 -d 1 2 3 4 5 6 7 8 9 10

# Config
bspc config top_padding         -21
bspc config border_width        3
bspc config window_gap          35
bspc config borderless_monocle  false
bspc config gapless_monocle     false

# Window colours

# focused window
bspc config active_border_color          '#186150'

# focused window + focused monitor
bspc config focused_border_color         '#1c728c'

# unfocused window
bspc config normal_border_color          '#021B21'

# preselection border
bspc config presel_border_color          '#E8DFD6'

bspc config normal_locked_border_color   '#A2DCC3'
bspc config focused_locked_border_color  '#CFE5A7'
bspc config active_locked_border_color   '#FB7AA1'
