# #!/usr/bin/env bash

cd $HOME

export PATH="/usr/local/bin:/usr/local/sbin:/opt/X11/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export LANG="en_NZ.UTF-8"
export LC_CTYPE="en_NZ.UTF-8"

# load fonts
xset +fp ~/Library/Fonts
xset +fp ~/.fonts
xset fp rehash

# merge defaults
xrdb -cpp cpp $HOME/.Xresources

# set the cursor
xsetroot -cursor_name left_ptr

# no bell
xset -b

# start urxvt daemon
urxvtd -q -o -f &

# start wm
exec >>~/.xsession-errors 2>&1
sxhkd -f 20 -c $HOME/.config/sxhkd/sxhkdrc &
exec bspwm -c $HOME/.config/bspwm/bspwmrc
