#!/usr/bin/env bash

export PATH="/usr/pkg/bin:/usr/pkg/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export LANG="en_NZ.UTF-8"
export LC_CTYPE="en_NZ.UTF-8"

# merge defaults
xrdb -merge $HOME/.Xresources &

# set the cursor
xsetroot -cursor_name left_ptr &

# super cursor
xset r rate 500 25

# no bell
xset -b

# start urxvt daemon
urxvtd -q -o -f &
urxvtc &

# start wm
sxhkd &
exec bspwm
