#!/usr/bin/env bash

export PATH="/usr/pkg/bin:/usr/pkg/sbin:/opt/X11/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export LANG="en_NZ.UTF-8"
export LC_CTYPE="en_NZ.UTF-8"

# load fonts
xset fp=$HOME/.fonts &
xset fp rehash &

# merge defaults
xrdb -cpp cpp $HOME/.Xresources &

# set the cursor
xsetroot -cursor_name left_ptr &

# no bell
xset -b &

# start urxvt daemon
urxvtd -q -o -f &

# start wm
sxhkd -f 20 &
exec bspwm
