#!/usr/bin/env bash

BAR_SCRIPT=~/dotfiles/chromebook/bar/reader

# pipe bspwm info to bar
[ -e $PANEL_FIFO ] & rm $PANEL_FIFO
mkfifo $PANEL_FIFO

# BSPWM events
bspc control --subscribe | uq > $PANEL_FIFO &

# Active window title
xtitle -sf 'T%s' | uq > $PANEL_FIFO &

# Date
clock -s -i 60 -f 'D%a %d/%m' | uq > $PANEL_FIFO &

# Time
clock -s -i 10 -f 'C%H:%M' | uq > $PANEL_FIFO &

# Battery state
battery -s -i 5 -f 'B%s' | uq > $PANEL_FIFO &

# Battery percentage
battery -s -i 15 -f 'P%i' | uq > $PANEL_FIFO &

# Current wifi status
essid -w wlp1s0 -s -i 5 -f 'X%s' | uq > $PANEL_FIFO &

# Run bar
BAR_SIZE='1366x25+0+0'
BAR_FONT_1='-misc-tamzen-medium-r-normal--14-*-*-*-*-*-*-*'
BAR_FONT_2='-misc-stlarch-medium-r-normal--10-*-*-*-*-*-*-*'
BAR_FG='#FF232328'
BAR_BG='#FFD8E2EB'
BAR_OPTIONS="-g $BAR_SIZE -f $BAR_FONT_1,$BAR_FONT_2 -B $BAR_BG -F $BAR_FG -p"

cat $PANEL_FIFO | $BAR_SCRIPT | bar $BAR_OPTIONS
