export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

xrdb -merge $HOME/.Xresources

xmodmap $HOME/.Xmodmap

sh $HOME/.fehbg

setxkbmap -model pc104 -layout us -variant colemak

xset fp default
xset +fp ~/.fonts
xset fp rehash

sxhkd &
urxvtd -q -o -f &
exec bspwm
