export LANG="en_NZ.UTF-8"
export LC_CTYPE="en_NZ.UTF-8"

xrdb -merge .Xresources

sh ~/.fehbg

setxkbmap -model pc104 -layout us -variant colemak

xset fp default
xset +fp ~/.fonts
xset fp rehash

sxhkd &
urxvtd -q -o -f &
exec bspwm
