#!/usr/bin/env/bash

# Takes the input from reader and returns the formatted output

# Bar Colours
# 0 = background
# 1 = foreground
# 2 = grey bg
# 3 = grey text
# 4 = red
# 5 = green
# 6 = orange
# 7 = yellow
# 8 = blue
# 9 = magenta

# Icons
bat=$(echo -e '\u11B') # battery
clk=$(echo -e '\u110') # clock
sep="|"

battery=""
time=""

function print_right () {
  right="\r\f1${essid} \f5${sep} \f1${battery}% \f5${sep} \f1${time}\fr "
  # right="\r\f1${time}\fr "
}

function print_title () {
  title="  ${line#?}"
}

function print_left () {
  # left=""
  # IFS=':'
  # set -- ${line#?}
  # while [ $# -gt 0 ] ; do
  #   item=$1
  #   id=${item#?}
  #   name="  ${tags[$id]}  "
  #   case $item in
  #     u*)
  #       # urgent desktop
  #       left="$left\\b2\\f0${name}\\fr\\br"
  #       ;;
  #     [DU][0-9])
  #       # active desktop
  #       left="$left\\u5\\b2\\f5${name}\\fr\\br\\ur"
  #       ;;
  #     d*)
  #       # inactive but occupied desktop
  #       left="$left\\f1${name}\\fr"
  #       ;;
  #     E*)
  #       # inactive desktop
  #       left="$left\\f3${name}\\fr"
  #       ;;
  #     L*)
  #       # layout
  #       label="${id:0:1}"
  #       left="$left \\f6[ ${label} ]\\fr"
  #       ;;
  #   esac
  #   shift
  # done

  left=""
  IFS=':'
  set -- ${line#?}
  while [ $# -gt 0 ] ; do
    item=$1
    name="  ${item#?}  "
    case $item in
      O*)
        # focused occupied desktop
        left="$left\\u5\\b2\\f5${name}\\ur\\br\\fr"
        ;;
      F*)
        # focused free desktop
        left="$left\\u2\\b2\\f1${name}\\ur\\br\\fr"
        ;;
      U*)
        # focused urgent desktop
        left="$left\\u9\\f0${name}\\ur\\f0"
        ;;
      o*)
        # occupied desktop
        left="$left\\u5\\f1${name}\\ur\\fr"
        ;;
      f*)
        # free desktop
        left="$left\\f3${name}\\fr"
        ;;
      u*)
        # urgent desktop
        left="$left\\b1${name}\\br"
        ;;
      L*)
        # layout
        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
        left="$left \\f2$layout\\fr"
        ;;
    esac
    shift
  done

}
