# use colemak
setxkbmap us -variant colemak -option ctrl:nocaps -option altwin:swap_alt_win

# set background colour based on battery level
(
  while true; do
    xsetroot-battery
    sleep 10
  done
) &

# wm keybindings
export XDG_CACHE_HOME=/home/admin/.cache
export XDG_CONFIG_HOME=/home/admin/.config
export XDG_DATA_HOME=/home/admin/.local/share
export XDG_RUNTIME_DIR=/home/admin
export XDG_STATE_HOME=/home/admin/.local/state
export SXHKD_SHELL=/bin/bash
export PATH=$HOME/dotfiles/bin:$PATH
sxhkd -c /home/admin/.config/sxhkd/sxhkdrc &

exec bspwm -c /home/admin/.config/bspwm/bspwmrc
