# use colemak
setxkbmap us -variant colemak -option ctrl:nocaps -option altwin:swap_alt_win

# set background colour
xsetroot -solid '#001115'

# wm keybindings
XDG_RUNTIME_DIR=/tmp SXHKD_SHELL=/bin/bash PATH=$HOME/dotfiles/bin:$PATH sxhkd &

exec bspwm -c /home/admin/.config/bspwm/bspwmrc
