export LANG="en_NZ.UTF-8"
export LC_CTYPE="en_NZ.UTF-8"

# use colemak
setxkbmap us -variant colemak -option ctrl:nocaps -option altwin:swap_alt_win

# set background colour
xsetroot -solid '#001115'

# wm keybindings
sxhkd -m 1 &

exec bspwm
