#!/bin/bash

# Color and echo
e="echo -e"
c0="\033[0m"    # Reset
c1="\033[0;32m" # Green
c2="\033[0;33m" # Yellow
c3="\033[1;31m" # RED
c4="\033[0;31m" # Red
c5="\033[0;35m" # Purple
c6="\033[0;36m" # Blue
c7="\033[1;31m" # BLUE

# OS information
OS=$(sw_vers|awk '/ProductName/{print $2, $3, $4}')
VERS=$(sw_vers|awk '/ProductVersion/{print $2}')
BUILD=$(sw_vers|awk '/BuildVersion/{print $2}')
WM=$(echo Zephyros)
RAM=$(system_profiler SPHardwareDataType | awk '/Memory/{print $2,$3}')
CPU_TYPE=$(system_profiler SPHardwareDataType | awk '/Processor Name/{print $3,$4,$5,$6,$7}')
CPU_FR=$(system_profiler SPHardwareDataType | awk '/Processor Speed/{print $3,$4,$5,$6,$7}')
VCARD=$(system_profiler SPDisplaysDataType | awk '/Chipset/{print $3,$4,$5}')
VRAM=$(system_profiler SPDisplaysDataType | awk '/VRAM/{print $3,$4,$5,$6,$7}')
# MODEL=$(system_profiler SPHardwareDataType | awk '/Model Identifier/{print $3,$4,$5,$6,$7}')
MODEL=$(echo Hackintosh)
DISK_USAGE=$(df | awk '/disk0s2/{print$5}')
PACKAGES=$(brew list | wc -l | awk '{print substr($0,7,10)}')
SHELL=$(echo $SHELL)
RES=$(system_profiler SPDisplaysDataType | awk '/Resolution/{print $2,$3,$4}' | head -n 1)
UPTIME=$(system_profiler SPSoftwareDataType | awk '/boot/{print $4, $5, $6, $7, $8}')
# Printing the apple

$e ""
$e ""
$e ""

$e "${c1}                :++++.         "   "${c7}`users`${c5}@${c7}`hostname`"
$e "${c1}               /+++/.          "   "${c7}OS: ${c0}$OS $VERS ($BUILD)"
$e "${c1}       .:-::- .+/:-\`\`.::-    "   "  ${c7}Kernel: ${c0}`uname -mrs`"
$e "${c1}    .:/++++++/::::/++++++/:\`  "   " ${c7}Uptime: ${c0}$UPTIME"
$e "${c2}  .:///////////////////////:\` "   " ${c7}Packages: ${c0}$PACKAGES"
$e "${c2}  ////////////////////////\`   "   " ${c7}Shell: ${c0}$SHELL"
$e "${c3} -+++++++++++++++++++++++\`    "   " ${c7}Resolution: ${c0}$RES"
$e "${c3} /++++++++++++++++++++++/      "   "${c7}DE: ${c0}Minimal"
$e "${c4} /sssssssssssssssssssssss.     "   "${c7}WM: ${c0}$WM"
$e "${c4} :ssssssssssssssssssssssss-    "   "${c7}Ram: ${c0}$RAM"
$e "${c5}  osssssssssssssssssssssssso/\\"   " ${c7}Cpu: ${c0}$CPU_TYPE @ $CPU_FR"
$e "${c5}  \`syyyyyyyyyyyyyyyyyyyyyyyy+\\"  " ${c7}VRam: ${c0}$VCARD @ $VRAM"
$e "${c6}   \`ossssssssssssssssssssss/   "  "${c7}Model: ${c0}$MODEL"
$e "${c6}     :ooooooooooooooooooo+.    "   "${c7}Disk Usage: ${c0}$DISK_USAGE"
$e "${c6}      \`:+oo+/:-..-:/+o+/-   "     "   ${c7}Term: ${c0}iTerm2"

$e ""
$e ""
$e ""
$e ""

## TODO: packages-1, wm, de 1
