#!/bin/bash
#
#   This file echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).
#

# Text to display
T='gYw';

echo '      b' \
     '      0' \
     '      1' \
     '      2' \
     '      3' \
     '      4' \
     '      5' \
     '      6' \
     '      7';
I=0;

declare -a colors=(
  "f "
  "0 " "8 " "1 " "9 " "2 " "10" "3 " "11"
  "4 " "12" "5 " "13" "6 " "14" "7 " "15")

for FGs in '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m';
  do FG=${FGs// /}

  # Print color on default bg
  echo -en "${colors[$I]} \033[$FG  $T  "

  # Print on custom bg
  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
    do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
  done

  # Increment I
  I=`expr $I + 1`

  echo;
done

echo
