#!/usr/bin/env bash

# Config
bspc config top_padding         0
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      button1

# Create monitors
bspc monitor eDP1 -d 1 2 3 4 5
# bspc monitor HDMI1 -d 6 7 8 9 10

# Set windows styles
for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 4
  bspc config -d $desktop window_gap   8
done

# focused window
bspc config focused_border_color         '#247C94'

# unfocused window
bspc config normal_border_color          '#0A2229'

# preselection border
bspc config presel_feedback_color        '#0A2229'
