# osx only
# cd $HOME
# xset r rate 500 25
# stty -ixon

# path
export GOPATH=$HOME/go
export PATH=/usr/local/bin:/usr/bin:/bin:/opt/X11/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/heroku/bin:/usr/local/go/bin:$GOPATH/bin

# neovim
alias vim='nvim'
alias vi='nvim'

# ls colors
alias ls='gls -hF --color=auto --group-directories-first'
eval $(gdircolors -b ~/dotfiles/apps/zsh/dircolors)

source ~/dotfiles/apps/zsh/config
