# osx only
cd $HOME
xset r rate 500 25
stty -ixon

# path
export GOPATH=$HOME/go
export PATH=/usr/pkg/bin:/usr/local/bin:/usr/bin:/bin:/usr/pkg/sbin:/usr/sbin:/sbin:/usr/local/heroku/bin:/usr/local/go/bin:$GOPATH/bin
export MANPATH=/usr/pkg/man:/usr/pkg/share/man:/usr/local/share/man:/usr/share/man

source ~/dotfiles/apps/zsh/config
